import os
from datetime import datetime

class DataVizAgent:
    def __init__(self):
        self.output_dir = "outputs"
        os.makedirs(self.output_dir, exist_ok=True)

    def generate(self, spec):
        print("DATAVIZ AGENT: Generating dashboard with file upload and ML...")
        files = {}

        files['index.html'] = self.generate_html()
        files['styles.css'] = self.generate_css()
        files['app.js'] = self.generate_js()
        files['server.js'] = self.generate_server()
        files['package.json'] = self.generate_package()

        self.write_files(files)
        return files

    def generate_html(self):
        return f"""<!DOCTYPE html>
<html>
<head>
  <title>Agri DataViz Dashboard</title>
  <link rel="stylesheet" href="styles.css">
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/papaparse@5.4.1/papaparse.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>
</head>
<body>
  <!-- Generated by DataVizAgent on {datetime.now().isoformat()} -->
  <div class="container">
    <h1>📊 Agri-Climate Dashboard</h1>
    
    <!-- FILE UPLOAD DROP ZONE -->
    <div class="upload-zone" id="uploadZone">
      <div class="upload-icon">📁</div>
      <p><strong>Drag & Drop Excel/CSV/JSON</strong><br>
      <small>or click to browse (max 10MB)</small></p>
      <input type="file" id="fileInput" accept=".csv,.xlsx,.xls,.json" style="display:none;">
      <button onclick="document.getElementById('fileInput').click()" class="btn">Browse Files</button>
    </div>

    <!-- SAMPLE DATA BUTTON -->
    <div class="sample-data">
      <button onclick="loadSampleData()" class="btn btn-secondary">📈 Load Sample Agri Data</button>
    </div>

    <!-- DATA PREVIEW -->
    <div id="dataPreview" class="preview-section" style="display:none;">
      <h3>📋 Data Preview (<span id="rowCount">0</span> rows)</h3>
      <div id="tablePreview" class="table-container"></div>
    </div>

    <!-- CHARTS SECTION -->
    <div id="chartsSection" style="display:none;">
      <h3>📊 Visualizations</h3>
      <div class="chart-row">
        <div class="chart-container">
          <canvas id="lineChart"></canvas>
        </div>
        <div class="chart-container">
          <canvas id="barChart"></canvas>
        </div>
      </div>
      <div class="chart-row">
        <div class="chart-container">
          <canvas id="scatterChart"></canvas>
        </div>
        <div class="chart-container">
          <canvas id="pieChart"></canvas>
        </div>
      </div>
    </div>

    <!-- ML ANOMALIES -->
    <div id="anomaliesSection" class="anomalies-section" style="display:none;">
      <h3>🚨 ML Anomaly Detection</h3>
      <div id="anomalies"></div>
    </div>
  </div>

  <script src="app.js"></script>
</body>
</html>"""

    def generate_css(self):
        return """/* DataViz Dashboard Styles - Agriculture Green Theme */
* { box-sizing: border-box; margin: 0; padding: 0; }
body { 
  font-family: 'Segoe UI', sans-serif; 
  background: linear-gradient(135deg, #2d5016 0%, #4a7c2e 50%, #6b9b47 100%); 
  min-height: 100vh; 
  padding: 20px;
}

.container { 
  max-width: 1400px; 
  margin: auto; 
  background: #f8faf5; 
  border-radius: 20px; 
  box-shadow: 0 25px 50px rgba(0,0,0,0.3); 
  padding: 40px;
  overflow: hidden;
}

h1 { 
  text-align: center; 
  color: #2d5016; 
  margin-bottom: 40px; 
  font-size: 2.5rem;
}

h3 {
  color: #2d5016;
  margin-bottom: 20px;
  font-size: 1.5rem;
}

/* UPLOAD ZONE */
.upload-zone { 
  border: 3px dashed #4a7c2e; 
  border-radius: 20px; 
  padding: 60px 40px; 
  text-align: center; 
  background: #edf5e8; 
  margin-bottom: 30px;
  transition: all 0.3s ease;
  cursor: pointer;
}

.upload-zone:hover, .upload-zone.dragover { 
  border-color: #6b9b47; 
  background: #e0eed9; 
  transform: scale(1.02);
}

.upload-icon { 
  font-size: 4rem; 
  margin-bottom: 20px; 
  opacity: 0.8;
}

.upload-zone p { 
  color: #2d5016; 
  font-size: 1.2rem; 
  margin-bottom: 20px;
}

.upload-zone small { 
  color: #5a7a3c; 
  font-size: 0.9rem;
}

/* BUTTONS */
.sample-data {
  text-align: center;
  margin-bottom: 30px;
}

.btn { 
  background: linear-gradient(135deg, #4a7c2e 0%, #6b9b47 100%); 
  color: white; 
  border: none; 
  padding: 12px 30px; 
  border-radius: 25px; 
  font-size: 1rem; 
  cursor: pointer; 
  transition: all 0.3s;
  margin: 5px;
}

.btn:hover { 
  background: linear-gradient(135deg, #3d6525 0%, #588237 100%); 
  transform: translateY(-2px);
  box-shadow: 0 10px 20px rgba(74, 124, 46, 0.3);
}

.btn-secondary { 
  background: #7fb069;
}

.btn-secondary:hover { 
  background: #6a9657;
}

/* PREVIEW */
.preview-section { 
  background: #ffffff; 
  padding: 25px; 
  border-radius: 15px; 
  margin: 30px 0;
  border: 1px solid #d4e4c8;
}

.table-container { 
  max-height: 300px; 
  overflow: auto; 
  border: 1px solid #d4e4c8; 
  border-radius: 10px;
}

table { 
  width: 100%; 
  border-collapse: collapse; 
  font-size: 0.9rem;
}

th, td { 
  padding: 12px; 
  text-align: left; 
  border-bottom: 1px solid #e8f0e3;
}

th { 
  background: #4a7c2e; 
  color: white; 
  position: sticky; 
  top: 0;
}

tr:hover {
  background: #f5f9f3;
}

/* CHARTS */
#chartsSection {
  margin: 30px 0;
}

.chart-row { 
  display: grid; 
  grid-template-columns: 1fr 1fr; 
  gap: 30px; 
  margin: 30px 0;
}

.chart-container {
  background: white;
  border-radius: 15px;
  padding: 20px;
  box-shadow: 0 10px 30px rgba(0,0,0,0.1);
}

canvas { 
  width: 100% !important;
  height: 300px !important;
}

/* ANOMALIES */
.anomalies-section { 
  background: linear-gradient(135deg, #fff8e1 0%, #ffe9a0 100%); 
  border: 2px solid #f9a825; 
  border-radius: 15px; 
  padding: 30px; 
  margin-top: 30px;
}

#anomalies ul { 
  list-style: none; 
  padding: 0;
}

#anomalies li { 
  background: white; 
  margin: 10px 0; 
  padding: 15px; 
  border-radius: 10px; 
  border-left: 5px solid #f57c00;
}

/* RESPONSIVE */
@media (max-width: 768px) {
  .chart-row { grid-template-columns: 1fr; }
  .container { padding: 20px; }
  h1 { font-size: 2rem; }
}"""

    def generate_js(self):
        return """// app.js - Drag & Drop Excel/CSV/JSON → Instant Charts + ML Anomalies
let rawData = [];
let processedData = [];
let numericColumns = [];
let charts = {};

const fileInput = document.getElementById('fileInput');
const uploadZone = document.getElementById('uploadZone');
const dataPreview = document.getElementById('dataPreview');
const chartsSection = document.getElementById('chartsSection');
const anomaliesSection = document.getElementById('anomaliesSection');

// === 1. FILE UPLOAD HANDLERS ===
uploadZone.addEventListener('click', (e) => {
  if (e.target === uploadZone || e.target.classList.contains('upload-icon') || e.target.tagName === 'P' || e.target.tagName === 'SMALL') {
    fileInput.click();
  }
});

uploadZone.addEventListener('dragover', (e) => {
  e.preventDefault();
  e.stopPropagation();
  uploadZone.classList.add('dragover');
});

uploadZone.addEventListener('dragleave', (e) => {
  e.preventDefault();
  e.stopPropagation();
  uploadZone.classList.remove('dragover');
});

uploadZone.addEventListener('drop', (e) => {
  e.preventDefault();
  e.stopPropagation();
  uploadZone.classList.remove('dragover');
  const files = e.dataTransfer.files;
  if (files.length > 0) {
    handleFiles(files);
  }
});

fileInput.addEventListener('change', (e) => {
  if (e.target.files.length > 0) {
    handleFiles(e.target.files);
  }
});

// === 2. PROCESS FILES ===
function handleFiles(files) {
  console.log('Files received:', files.length);
  
  for (let file of Array.from(files)) {
    console.log('Processing file:', file.name, 'Type:', file.type);
    const ext = file.name.split('.').pop().toLowerCase();
    
    if (ext === 'csv') {
      console.log('Parsing CSV file...');
      Papa.parse(file, {
        header: true,
        skipEmptyLines: true,
        dynamicTyping: true,
        complete: (results) => {
          console.log('CSV parsed successfully:', results.data.length, 'rows');
          processData(results.data);
        },
        error: (error) => {
          console.error('CSV parsing error:', error);
          alert('Error parsing CSV file: ' + error.message);
        }
      });
    } 
    else if (ext === 'json') {
      console.log('Reading JSON file...');
      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const data = JSON.parse(e.target.result);
          console.log('JSON parsed successfully');
          processData(Array.isArray(data) ? data : Object.values(data));
        } catch (error) {
          console.error('JSON parsing error:', error);
          alert('Error parsing JSON file: ' + error.message);
        }
      };
      reader.onerror = (error) => {
        console.error('File reading error:', error);
        alert('Error reading file');
      };
      reader.readAsText(file);
    }
    else if (ext === 'xlsx' || ext === 'xls') {
      console.log('Reading Excel file...');
      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const data = new Uint8Array(e.target.result);
          const workbook = XLSX.read(data, { type: 'array' });
          const firstSheetName = workbook.SheetNames[0];
          const worksheet = workbook.Sheets[firstSheetName];
          const jsonData = XLSX.utils.sheet_to_json(worksheet, { header: 1 });
          
          // Convert to object array with headers
          const headers = jsonData[0];
          const rows = jsonData.slice(1).map(row => {
            const obj = {};
            headers.forEach((header, i) => {
              obj[header] = row[i];
            });
            return obj;
          });
          
          console.log('Excel parsed successfully:', rows.length, 'rows');
          processData(rows);
        } catch (error) {
          console.error('Excel parsing error:', error);
          alert('Error parsing Excel file: ' + error.message);
        }
      };
      reader.onerror = (error) => {
        console.error('File reading error:', error);
        alert('Error reading Excel file');
      };
      reader.readAsArrayBuffer(file);
    } else {
      alert('Unsupported file format. Please upload CSV, JSON, or Excel files.');
    }
  }
}

// === 3. PROCESS DATA ===
function processData(data) {
  console.log('Processing data:', data.length, 'rows');
  
  if (!data || data.length === 0) {
    alert('No data found in file');
    return;
  }
  
  rawData = data.filter(row => {
    return Object.values(row).some(val => val !== null && val !== undefined && val !== '');
  });
  
  console.log('Filtered data:', rawData.length, 'rows');
  
  if (rawData.length === 0) {
    alert('No valid data found in file');
    return;
  }
  
  processedData = rawData.map((row, i) => ({ ...row, index: i }));
  
  // Auto-detect numeric columns
  const firstRow = rawData[0];
  numericColumns = Object.keys(firstRow).filter(col => {
    const values = rawData.map(row => row[col]).filter(v => v !== '' && v != null && v !== undefined);
    if (values.length === 0) return false;
    
    // Check if at least 80% of values are numeric
    const numericCount = values.filter(v => !isNaN(parseFloat(v)) && isFinite(v)).length;
    return numericCount / values.length >= 0.8;
  });

  console.log('Numeric columns detected:', numericColumns);
  console.log('All columns:', Object.keys(firstRow));

  updatePreview();
  
  if (numericColumns.length >= 1) {
    generateCharts();
    runMLAnomalies();
  } else {
    alert('No numeric columns found in the data. Please ensure your file contains numeric values for visualization.');
  }
}

// === 4. DATA PREVIEW ===
function updatePreview() {
  document.getElementById('rowCount').textContent = rawData.length;
  
  const table = document.getElementById('tablePreview');
  if (rawData.length === 0) return;
  
  const cols = Object.keys(rawData[0]);
  let html = '<table><thead><tr>' + cols.map(c => '<th>' + c + '</th>').join('') + '</tr></thead><tbody>';
  
  rawData.slice(0, 10).forEach(row => {
    html += '<tr>' + cols.map(c => '<td>' + (row[c] !== null && row[c] !== undefined ? row[c] : '') + '</td>').join('') + '</tr>';
  });
  
  if (rawData.length > 10) {
    html += '<tr><td colspan="' + cols.length + '" style="text-align:center;color:#666;">... and ' + (rawData.length - 10) + ' more rows</td></tr>';
  }
  html += '</tbody></table>';
  
  table.innerHTML = html;
  dataPreview.style.display = 'block';
}

// === 5. GENERATE CHARTS ===
function generateCharts() {
  console.log('Generating charts...');
  
  // Clear old charts
  Object.values(charts).forEach(chart => {
    try {
      chart.destroy();
    } catch (e) {
      console.error('Error destroying chart:', e);
    }
  });
  charts = {};
  
  const ctx1 = document.getElementById('lineChart').getContext('2d');
  const ctx2 = document.getElementById('barChart').getContext('2d');
  const ctx3 = document.getElementById('scatterChart').getContext('2d');
  const ctx4 = document.getElementById('pieChart').getContext('2d');
  
  // Prepare labels (use first column if not numeric, else use row numbers)
  const labelColumn = Object.keys(rawData[0]).find(col => !numericColumns.includes(col));
  const labels = labelColumn 
    ? processedData.map(d => d[labelColumn] || 'Row ' + (d.index + 1))
    : processedData.map((_, i) => 'Row ' + (i + 1));
  
  // Line Chart - show up to 3 numeric columns
  const lineDatasets = numericColumns.slice(0, 3).map((col, i) => ({
    label: col,
    data: processedData.map(d => parseFloat(d[col]) || 0),
    borderColor: ['#4a7c2e', '#6b9b47', '#7fb069'][i],
    backgroundColor: ['rgba(74, 124, 46, 0.1)', 'rgba(107, 155, 71, 0.1)', 'rgba(127, 176, 105, 0.1)'][i],
    tension: 0.4,
    fill: true
  }));
  
  charts.line = new Chart(ctx1, {
    type: 'line',
    data: {
      labels: labels,
      datasets: lineDatasets
    },
    options: { 
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        title: {
          display: true,
          text: 'Line Chart - Trends Over Time'
        },
        legend: {
          display: true,
          position: 'top'
        }
      },
      scales: { 
        y: { 
          beginAtZero: true,
          grid: {
            color: 'rgba(0, 0, 0, 0.05)'
          }
        },
        x: {
          grid: {
            display: false
          }
        }
      }
    }
  });
  
  // Bar Chart - first numeric column
  charts.bar = new Chart(ctx2, {
    type: 'bar',
    data: {
      labels: labels.slice(0, 20), // Limit to 20 bars for readability
      datasets: [{
        label: numericColumns[0] || 'Value',
        data: processedData.slice(0, 20).map(d => parseFloat(d[numericColumns[0]]) || 0),
        backgroundColor: 'rgba(74, 124, 46, 0.7)',
        borderColor: '#4a7c2e',
        borderWidth: 1
      }]
    },
    options: { 
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        title: {
          display: true,
          text: 'Bar Chart - Value Comparison'
        },
        legend: {
          display: true
        }
      },
      scales: { 
        y: { 
          beginAtZero: true,
          grid: {
            color: 'rgba(0, 0, 0, 0.05)'
          }
        },
        x: {
          grid: {
            display: false
          }
        }
      }
    }
  });
  
  // Scatter Plot - if at least 2 numeric columns
  if (numericColumns.length >= 2) {
    charts.scatter = new Chart(ctx3, {
      type: 'scatter',
      data: {
        datasets: [{
          label: numericColumns[0] + ' vs ' + numericColumns[1],
          data: processedData.map(d => ({
            x: parseFloat(d[numericColumns[0]]) || 0,
            y: parseFloat(d[numericColumns[1]]) || 0
          })),
          backgroundColor: 'rgba(107, 155, 71, 0.6)',
          borderColor: '#6b9b47',
          borderWidth: 1,
          pointRadius: 5
        }]
      },
      options: { 
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          title: {
            display: true,
            text: 'Scatter Plot - Correlation Analysis'
          }
        },
        scales: {
          x: {
            title: {
              display: true,
              text: numericColumns[0]
            },
            grid: {
              color: 'rgba(0, 0, 0, 0.05)'
            }
          },
          y: {
            title: {
              display: true,
              text: numericColumns[1]
            },
            grid: {
              color: 'rgba(0, 0, 0, 0.05)'
            }
          }
        }
      }
    });
  } else {
    ctx3.canvas.parentElement.innerHTML = '<p style="text-align:center;padding:50px;color:#666;">Need at least 2 numeric columns for scatter plot</p>';
  }
  
  // Pie Chart - top 10 values from first numeric column
  const pieValues = processedData
    .map(d => parseFloat(d[numericColumns[0]]) || 0)
    .sort((a, b) => b - a)
    .slice(0, 10);
    
  const pieLabels = processedData
    .map((d, i) => ({ val: parseFloat(d[numericColumns[0]]) || 0, label: labels[i] }))
    .sort((a, b) => b.val - a.val)
    .slice(0, 10)
    .map(item => item.label);
    
  charts.pie = new Chart(ctx4, {
    type: 'pie',
    data: {
      labels: pieLabels,
      datasets: [{
        data: pieValues,
        backgroundColor: [
          '#4a7c2e', '#6b9b47', '#7fb069', '#a3c585', '#c7daa1',
          '#d4e4c8', '#5a7a3c', '#3d6525', '#588237', '#8db86e'
        ],
        borderWidth: 2,
        borderColor: '#fff'
      }]
    },
    options: { 
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        title: {
          display: true,
          text: 'Pie Chart - Top 10 Distribution'
        },
        legend: {
          display: true,
          position: 'right'
        }
      }
    }
  });
  
  chartsSection.style.display = 'block';
  console.log('Charts generated successfully');
}

// === 6. ML ANOMALY DETECTION ===
function runMLAnomalies() {
  if (numericColumns.length === 0) return;
  
  console.log('Running anomaly detection...');
  
  // Simple statistical anomaly detection (Z-score > 2)
  const values = processedData.map(d => parseFloat(d[numericColumns[0]]) || 0).filter(v => !isNaN(v));
  const mean = values.reduce((a, b) => a + b, 0) / values.length;
  const std = Math.sqrt(values.map(v => (v - mean) ** 2).reduce((a, b) => a + b, 0) / values.length);
  
  const anomalies = processedData
    .map((row, i) => {
      const val = parseFloat(row[numericColumns[0]]) || 0;
      const zscore = Math.abs((val - mean) / std);
      return { index: i, value: val, zscore: zscore.toFixed(2), row };
    })
    .filter(a => parseFloat(a.zscore) > 2)
    .slice(0, 10);
  
  displayAnomalies(anomalies, mean, std);
}

function displayAnomalies(anomalies, mean, std) {
  const div = document.getElementById('anomalies');
  if (anomalies.length === 0) {
    div.innerHTML = '<div style="color:#2d5016;font-size:1.1rem;text-align:center;">✅ No anomalies detected. Data looks normal!</div>';
  } else {
    div.innerHTML = `
      <div style="font-size:1.1rem;margin-bottom:15px;">
        🚨 <strong>${anomalies.length}</strong> outliers detected (Z-score > 2σ)
        <br><small style="color:#5a7a3c;">Mean: ${mean.toFixed(2)} | Standard Deviation: ${std.toFixed(2)}</small>
      </div>
      <ul>
        ${anomalies.map(a => `
          <li>
            <strong>Row ${a.index + 1}:</strong> Value = ${a.value.toFixed(2)} 
            <span style="color:#f57c00;font-weight:bold;">(Z-score = ${a.zscore})</span>
            <br><small style="color:#666;">${Object.keys(a.row).slice(0, 3).map(k => k + ': ' + a.row[k]).join(' | ')}</small>
          </li>
        `).join('')}
      </ul>
    `;
  }
  anomaliesSection.style.display = 'block';
}

// === 7. SAMPLE DATA ===
function loadSampleData() {
  const sample = [
    { Year: 2018, Rainfall: 1200, Wheat: 5000, Rice: 8000, Temperature: 28 },
    { Year: 2019, Rainfall: 1100, Wheat: 5200, Rice: 7900, Temperature: 29 },
    { Year: 2020, Rainfall: 800, Wheat: 4800, Rice: 7500, Temperature: 32 },
    { Year: 2021, Rainfall: 1300, Wheat: 5500, Rice: 8200, Temperature: 27 },
    { Year: 2022, Rainfall: 1150, Wheat: 5300, Rice: 8100, Temperature: 28 },
    { Year: 2023, Rainfall: 1250, Wheat: 5600, Rice: 8400, Temperature: 29 },
    { Year: 2024, Rainfall: 950, Wheat: 5100, Rice: 7800, Temperature: 31 }
  ];
  console.log('Loading sample data...');
  processData(sample);
}

// === 8. INIT ===
console.log('🚀 DataViz Dashboard Ready - Drag your CSV/JSON/Excel files!');
console.log('Supported formats: CSV, JSON, XLSX, XLS');
"""

    def generate_server(self):
        return """const express = require('express');
const path = require('path');
const app = express();

// Serve static files
app.use(express.static(path.join(__dirname, '.')));

// Catch-all handler
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});

app.listen(5000, () => {
  console.log('================================');
  console.log('📊 DataViz Dashboard + ML');
  console.log('🌐 http://localhost:5000');
  console.log('📁 Drag CSV/JSON/Excel files');
  console.log('================================');
});
"""

    def generate_package(self):
        return """{
  "name": "dataviz-dashboard",
  "version": "1.0.0",
  "description": "AI-Generated DataViz + ML Dashboard",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "dev": "nodemon server.js"
  },
  "dependencies": {
    "express": "^4.18.2"
  },
  "devDependencies": {
    "nodemon": "^3.0.1"
  }
}"""

    def write_files(self, files):
        for name, content in files.items():
            path = os.path.join(self.output_dir, name)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"   ✓ Wrote {path}")