import os
from datetime import datetime

class FrontendAgent:
    def __init__(self):
        self.agent_name = "FrontendAgent"
        self.output_dir = "outputs/frontend"
        
    def generate(self, task):
        """Generate frontend files based on task specification"""
        print(f"{self.agent_name}: Starting frontend generation...")
        
        project_name = task['project_name']
        entity = task['entity']
        features = task['features']
        
        files = {}
        
        print(f"   Generating index.html...")
        files['index.html'] = self.generate_html(project_name, entity, features)
        
        print(f"   Generating styles.css...")
        files['styles.css'] = self.generate_css()
        
        print(f"   Generating app.js...")
        files['app.js'] = self.generate_js(entity, features)
        
        self.write_files(files)
        
        return files
    
    def generate_html(self, project_name, entity, features):
        """Generate HTML structure"""
        has_search = 'search' in features
        has_categories = 'categories' in features
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{project_name}</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <!-- Generated by {self.agent_name} on {datetime.now().isoformat()} -->
    
    <div class="container">
        <header>
            <h1>📝 {project_name}</h1>
            <p class="subtitle">Powered by AI Agent System</p>
        </header>

        <main>
            <section class="add-section">
                <h2>Add New {entity.capitalize()}</h2>
                <form id="addForm">
                    <input 
                        type="text" 
                        id="{entity}Title" 
                        placeholder="Enter {entity} title..." 
                        required
                    />
                    <textarea 
                        id="{entity}Content" 
                        placeholder="Enter {entity} content..."
                        rows="3"
                    ></textarea>
                    {'<input type="text" id="' + entity + 'Category" placeholder="Category..." />' if has_categories else ''}
                    <button type="submit" class="btn btn-primary">Add {entity.capitalize()}</button>
                </form>
            </section>

            {'<section class="search-section">' if has_search else ''}
            {'    <input type="text" id="searchInput" placeholder="Search ' + entity + 's..." />' if has_search else ''}
            {'</section>' if has_search else ''}

            <section class="list-section">
                <h2>Your {entity.capitalize()}s</h2>
                <div id="{entity}List" class="items-grid">
                    <p class="empty-state">No {entity}s yet. Add one above!</p>
                </div>
            </section>
        </main>

        <footer>
            <p>Generated by AI Agent System | Frontend Agent v1.0</p>
        </footer>
    </div>

    <script src="app.js"></script>
</body>
</html>"""
        return html
    
    def generate_css(self):
        """Generate CSS styles - Fire Theme"""
        css = f"""/* Generated by {self.agent_name} on {datetime.now().isoformat()} */

* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

body {{
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background: linear-gradient(135deg, #ff6b35 0%, #f7931e 50%, #fdc830 100%);
    min-height: 100vh;
    padding: 20px;
}}

.container {{
    max-width: 1200px;
    margin: 0 auto;
    background: #fffaf0;
    border-radius: 20px;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
    overflow: hidden;
}}

header {{
    background: linear-gradient(135deg, #ff6b35 0%, #f7931e 100%);
    color: white;
    padding: 40px;
    text-align: center;
}}

header h1 {{
    font-size: 2.5rem;
    margin-bottom: 10px;
}}

.subtitle {{
    opacity: 0.9;
    font-size: 0.9rem;
}}

main {{
    padding: 40px;
}}

section {{
    margin-bottom: 40px;
}}

h2 {{
    color: #d84315;
    margin-bottom: 20px;
    font-size: 1.5rem;
}}

#addForm {{
    display: flex;
    flex-direction: column;
    gap: 15px;
}}

input[type="text"],
textarea {{
    padding: 15px;
    border: 2px solid #ffcc80;
    border-radius: 10px;
    font-size: 1rem;
    transition: all 0.3s;
    background: white;
}}

input[type="text"]:focus,
textarea:focus {{
    outline: none;
    border-color: #ff6b35;
    box-shadow: 0 0 0 3px rgba(255, 107, 53, 0.1);
}}

textarea {{
    resize: vertical;
    font-family: inherit;
}}

#searchInput {{
    width: 100%;
    padding: 15px;
    border: 2px solid #ffcc80;
    border-radius: 10px;
    font-size: 1rem;
}}

.btn {{
    padding: 15px 30px;
    border: none;
    border-radius: 10px;
    font-size: 1rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.3s;
}}

.btn-primary {{
    background: linear-gradient(135deg, #ff6b35 0%, #f7931e 100%);
    color: white;
}}

.btn-primary:hover {{
    transform: translateY(-2px);
    box-shadow: 0 10px 20px rgba(255, 107, 53, 0.3);
}}

.btn-danger {{
    background: #d84315;
    color: white;
    padding: 8px 16px;
    font-size: 0.9rem;
}}

.btn-danger:hover {{
    background: #bf360c;
}}

.items-grid {{
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 20px;
}}

.item-card {{
    background: white;
    border-radius: 15px;
    padding: 20px;
    border: 2px solid #ffcc80;
    transition: all 0.3s;
}}

.item-card:hover {{
    transform: translateY(-5px);
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
    border-color: #ff6b35;
}}

.item-card h3 {{
    color: #d84315;
    margin-bottom: 10px;
    font-size: 1.2rem;
}}

.item-card p {{
    color: #666;
    line-height: 1.6;
    margin-bottom: 15px;
}}

.item-meta {{
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 0.85rem;
    color: #999;
    margin-bottom: 15px;
}}

.item-category {{
    background: #ff6b35;
    color: white;
    padding: 4px 12px;
    border-radius: 20px;
    font-size: 0.8rem;
}}

.item-actions {{
    display: flex;
    gap: 10px;
}}

.empty-state {{
    text-align: center;
    color: #999;
    padding: 60px 20px;
    font-size: 1.1rem;
}}

footer {{
    background: #fff8f0;
    padding: 20px;
    text-align: center;
    color: #666;
    border-top: 1px solid #ffcc80;
}}

@media (max-width: 768px) {{
    header h1 {{
        font-size: 2rem;
    }}
    
    .items-grid {{
        grid-template-columns: 1fr;
    }}
}}"""
        return css
    
    def generate_js(self, entity, features):
        """Generate JavaScript application logic"""
        has_search = 'search' in features
        has_delete = 'delete' in features
        
        js = f"""// Generated by {self.agent_name} on {datetime.now().isoformat()}

const API_URL = '/api';

let {entity}s = [];

document.addEventListener('DOMContentLoaded', () => {{
    console.log('🚀 {self.agent_name}: Application initialized');
    loadAll{entity.capitalize()}s();
    setupEventListeners();
}});

function setupEventListeners() {{
    const form = document.getElementById('addForm');
    form.addEventListener('submit', handle{entity.capitalize()}Submit);
    
    {f'''const searchInput = document.getElementById('searchInput');
    searchInput.addEventListener('input', handleSearch);''' if has_search else ''}
}}

async function loadAll{entity.capitalize()}s() {{
    try {{
        const response = await fetch(`${{API_URL}}/{entity}s`);
        if (!response.ok) throw new Error('Failed to fetch {entity}s');
        
        {entity}s = await response.json();
        render{entity.capitalize()}s({entity}s);
        console.log('✓ Loaded ' + {entity}s.length + ' {entity}s');
    }} catch (error) {{
        console.error('Error loading {entity}s:', error);
        showError('Failed to load {entity}s. Is the backend running?');
    }}
}}

async function handle{entity.capitalize()}Submit(e) {{
    e.preventDefault();
    
    const titleInput = document.getElementById('{entity}Title');
    const contentInput = document.getElementById('{entity}Content');
    {f"const categoryInput = document.getElementById('{entity}Category');" if 'categories' in features else ''}
    
    const new{entity.capitalize()} = {{
        title: titleInput.value.trim(),
        content: contentInput.value.trim(),
        {f"category: categoryInput.value.trim()," if 'categories' in features else ''}
    }};
    
    try {{
        const response = await fetch(`${{API_URL}}/{entity}s`, {{
            method: 'POST',
            headers: {{ 'Content-Type': 'application/json' }},
            body: JSON.stringify(new{entity.capitalize()}),
        }});
        
        if (!response.ok) throw new Error('Failed to create {entity}');
        
        const created{entity.capitalize()} = await response.json();
        {entity}s.push(created{entity.capitalize()});
        render{entity.capitalize()}s({entity}s);
        
        titleInput.value = '';
        contentInput.value = '';
        {f"categoryInput.value = '';" if 'categories' in features else ''}
        
        console.log('✓ {entity.capitalize()} created successfully');
    }} catch (error) {{
        console.error('Error creating {entity}:', error);
        showError('Failed to create {entity}');
    }}
}}

{f'''function handleSearch(e) {{
    const query = e.target.value.toLowerCase();
    const filtered = {entity}s.filter({entity} => 
        {entity}.title.toLowerCase().includes(query) ||
        {entity}.content.toLowerCase().includes(query)
    );
    render{entity.capitalize()}s(filtered);
}}''' if has_search else ''}

{f'''async function delete{entity.capitalize()}(id) {{
    if (!confirm('Are you sure you want to delete this {entity}?')) return;
    
    try {{
        const response = await fetch(`${{API_URL}}/{entity}s/${{id}}`, {{
            method: 'DELETE',
        }});
        
        if (!response.ok) throw new Error('Failed to delete {entity}');
        
        {entity}s = {entity}s.filter({entity} => {entity}.id !== id);
        render{entity.capitalize()}s({entity}s);
        console.log('✓ {entity.capitalize()} deleted successfully');
    }} catch (error) {{
        console.error('Error deleting {entity}:', error);
        showError('Failed to delete {entity}');
    }}
}}''' if has_delete else ''}

function render{entity.capitalize()}s(items) {{
    const container = document.getElementById('{entity}List');
    
    if (items.length === 0) {{
        container.innerHTML = '<p class="empty-state">No {entity}s found.</p>';
        return;
    }}
    
    container.innerHTML = items.map({entity} => `
        <div class="item-card">
            <h3>${{{entity}.title}}</h3>
            <p>${{{entity}.content || 'No content'}}</p>
            <div class="item-meta">
                <span>${{formatDate({entity}.createdAt)}}</span>
                {f"${{" + entity + ".category ? `<span class='item-category'>${{" + entity + ".category}}</span>` : ''}}" if 'categories' in features else ''}
            </div>
            {f'''<div class="item-actions">
                <button class="btn btn-danger" onclick="delete{entity.capitalize()}('${{" + entity + ".id}}')">Delete</button>
            </div>''' if has_delete else ''}
        </div>
    `).join('');
}}

function formatDate(dateString) {{
    const date = new Date(dateString);
    return date.toLocaleDateString() + ' ' + date.toLocaleTimeString();
}}

function showError(message) {{
    alert(message);
}}

console.log('✅ {self.agent_name}: All functions loaded');"""
        return js
    
    def write_files(self, files):
        """Write generated files to disk"""
        for filename, content in files.items():
            filepath = os.path.join(self.output_dir, filename)
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"   Wrote {filepath}")