import os
from datetime import datetime

class WorldClockAgent:
    def __init__(self):
        self.output_dir = "outputs"
        os.makedirs(self.output_dir, exist_ok=True)

    def generate(self, spec):
        print("WORLDCLOCK AGENT: Generating live world clock...")
        files = {
            'index.html': self.generate_html(),
            'styles.css': self.generate_css(),
            'app.js': self.generate_js(),
            'server.js': self.generate_server(),
            'package.json': self.generate_package()
        }
        self.write_files(files)
        return files

    def generate_html(self):
        return f"""<!DOCTYPE html>
<html>
<head>
  <title>World Clock</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <!-- Generated by WorldClockAgent on {datetime.now().isoformat()} -->
  <div class="container">
    <h1>🌍 World Clock</h1>
    <p class="subtitle">Live time across the globe</p>
    <p id="local">Detecting your location...</p>
    <div id="clocks"></div>
  </div>
  <script src="app.js"></script>
</body>
</html>"""

    def generate_css(self):
        return """body { 
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
  background: linear-gradient(135deg, #1e3c72 0%, #2a5298 50%, #7e92b7 100%); 
  color: white; 
  padding: 20px; 
  margin: 0;
  min-height: 100vh;
}
.container { 
  max-width: 1200px; 
  margin: auto; 
  text-align: center; 
}
h1 {
  font-size: 3rem;
  margin-bottom: 10px;
  text-shadow: 2px 2px 10px rgba(0,0,0,0.3);
}
.subtitle {
  font-size: 1.2rem;
  opacity: 0.8;
  margin-bottom: 30px;
}
#local {
  font-size: 1.1rem;
  margin-bottom: 40px;
  padding: 15px;
  background: rgba(255,255,255,0.1);
  border-radius: 10px;
  display: inline-block;
  border: 1px solid rgba(255,255,255,0.2);
}
#clocks {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 25px;
  margin-top: 30px;
}
.clock { 
  padding: 30px; 
  background: rgba(255,255,255,0.1); 
  border-radius: 20px; 
  backdrop-filter: blur(10px);
  border: 2px solid rgba(255,255,255,0.2);
  transition: all 0.3s ease;
}
.clock:hover {
  transform: translateY(-5px);
  box-shadow: 0 10px 30px rgba(0,0,0,0.3);
  border-color: rgba(255,255,255,0.4);
  background: rgba(255,255,255,0.15);
}
.time { 
  font-size: 2.5rem; 
  font-weight: bold; 
  margin-bottom: 10px;
  font-family: 'Courier New', monospace;
}
.city { 
  font-size: 1.2rem; 
  opacity: 0.9; 
  margin-top: 10px;
}
.date {
  font-size: 0.9rem;
  opacity: 0.7;
  margin-top: 5px;
}"""

    def generate_js(self):
        return """const cities = [
  { name: "New York", zone: "America/New_York", flag: "🇺🇸" },
  { name: "London", zone: "Europe/London", flag: "🇬🇧" },
  { name: "Tokyo", zone: "Asia/Tokyo", flag: "🇯🇵" },
  { name: "Sydney", zone: "Australia/Sydney", flag: "🇦🇺" },
  { name: "Mumbai", zone: "Asia/Kolkata", flag: "🇮🇳" },
  { name: "Dubai", zone: "Asia/Dubai", flag: "🇦🇪" },
  { name: "Paris", zone: "Europe/Paris", flag: "🇫🇷" },
  { name: "Singapore", zone: "Asia/Singapore", flag: "🇸🇬" }
];

function updateClocks() {
  const container = document.getElementById('clocks');
  container.innerHTML = cities.map(city => {
    const now = new Date();
    const time = now.toLocaleTimeString('en-US', { 
      timeZone: city.zone, 
      hour: '2-digit', 
      minute: '2-digit', 
      second: '2-digit',
      hour12: true
    });
    const date = now.toLocaleDateString('en-US', {
      timeZone: city.zone,
      weekday: 'short',
      month: 'short',
      day: 'numeric'
    });
    return `
      <div class="clock">
        <div class="time">${time}</div>
        <div class="city">${city.flag} ${city.name}</div>
        <div class="date">${date}</div>
      </div>
    `;
  }).join('');
}

setInterval(updateClocks, 1000);
updateClocks();

// Auto-detect user location
fetch('https://ipapi.co/json/')
  .then(r => r.json())
  .then(data => {
    document.getElementById('local').innerHTML = `📍 Your location: <strong>${data.city}, ${data.region}</strong> (${data.timezone})`;
  })
  .catch(err => {
    document.getElementById('local').innerHTML = '📍 Location detection unavailable';
    console.error('Location detection error:', err);
  });
"""

    def generate_server(self):
        return """const express = require('express');
const app = express();
app.use(express.static('.'));

const PORT = 5000;
app.listen(PORT, () => {
  console.log('================================');
  console.log('🌍 World Clock Live');
  console.log(`🔗 URL: http://localhost:${PORT}`);
  console.log('================================');
});
"""

    def generate_package(self):
        return """{
  "name": "worldclock",
  "version": "1.0.0",
  "description": "Auto-generated World Clock Application",
  "main": "server.js",
  "dependencies": {
    "express": "^4.18.2"
  },
  "scripts": {
    "start": "node server.js"
  },
  "author": "AI Agent System - WorldClockAgent",
  "license": "MIT"
}
"""

    def write_files(self, files):
        for name, content in files.items():
            path = os.path.join(self.output_dir, name)
            with open(path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"   ✓ Wrote {path}")